### ISSUE TITLE
FLUTTER_MAP RELATIONS: New Documentation

### ISSUE THREAD

**Issue by JaffaKetchup** [greensopinion/flutter-vector-map-tiles#11]
_This message has been sent to multiple plugin authors, so it is not personalised_

As part of https://github.com/fleaflet/flutter_map/pull/992 & https://github.com/fleaflet/flutter_map/discussions/927#discussioncomment-1135466, I (a documentation author) am contacting plugin authors to ensure the information about this plugin on the new documentation is correct; or alternatively, if this plugin is not yet on the existing list, to check whether you would like to add your plugin to the new documentation.

I would also like you to check you conform to these new rules:
 - this plugin is available via a pub.dev installation to make it easier for developers - if your plugin does not currently have a pub.dev page, please add one or let me know otherwise,
 - the plugin documentation includes enough information for installation and basic setup/functionality,
 - the plugin includes a runnable example and/or screenshots,
 - the plugin description contains the words ' - IN BETA' after the author link on the same line if your plugin is in beta,

Currently I have copied over the existing plugin descriptions, and you can see these here: https://flutter-map.vercel.app/plugins/list. Please note that this documentation is currently unapproved and should not be used unless otherwise directed, as some information may be incorrect or missing, or might change in the future. There is no ETA at the moment, but things seem to be moving along.

Should you wish for the description to remain the same as current on the page linked above, you do not have to reply, you can close this issue.

If you wish to change any information, please leave this issue open and add your reply as a comment.

`flutter_map` maintainers do not take any responsibility for this message, I am the sole author.

On behalf of myself and the `flutter_map` community thank you for your excellent plugin :).

**Comment by greensopinion** [comment]
Hey, thanks for reaching out! It would be great to have this plugin included in the documentation.

To answer your questions:

> this plugin is available via a pub.dev installation to make it easier for developers - if your plugin does not currently have a pub.dev page, please add one or let me know otherwise,

Yes, you can find it here: https://pub.dev/packages/vector_map_tiles

> the plugin documentation includes enough information for installation and basic setup/functionality,

Yes, see https://pub.dev/packages/vector_map_tiles/example and API docs such as [VectorTileLayerOptions](https://pub.dev/documentation/vector_map_tiles/latest/vector_map_tiles/VectorTileLayerOptions-class.html)

> the plugin includes a runnable example and/or screenshots,

Yes, see https://github.com/greensopinion/flutter-vector-map-tiles/tree/main/example and a screenshot here: https://github.com/greensopinion/flutter-vector-map-tiles

> the plugin description contains the words ' - IN BETA' after the author link on the same line if your plugin is in beta,

n/a, it's not in beta

> Currently I have copied over the existing plugin descriptions, and you can see these here: https://flutter-map.vercel.app/plugins/list

I don't see [vector_map_tiles](https://pub.dev/packages/vector_map_tiles) in the list, it would be great to have it added!

Also https://flutter-map.vercel.app/miscellaneous/vector-tiles could refer to this plug-in.

> If you wish to change any information, please leave this issue open and add your reply as a comment.

https://github.com/fleaflet/flutter_map/pull/928 provides a minimal addition to the readme, feel free to improve on it

A good description of [vector_map_tiles](https://pub.dev/packages/vector_map_tiles) is provided:

> A plugin for flutter_map that enables the use of vector tiles with slippy maps and Flutter.
> 
> Loads vector tiles from a source such as Mapbox or Stadia Maps, and renders them as a layer on a flutter_map.
> 
> Tile rendering can be vector, mixed, or raster. Mixed mode is default, since that provides an optimal trade-off between sharp visuals when idle, and smooth animation when zooming with a pinch gesture.

**Comment by JaffaKetchup** [comment]
Sure, no problem!

I will link to (at least) the plugin list on that misc/vector-tiles page, as I am in two minds whether I should link directly to 3rd party plugins throughout documentation where necessary or whether I should just link to the plugins list to avoid 'advertising'. Whatever I chose I'll add your plugin the same as others (I'm trying to keep things roughly equal).

I'll use this short description on the plugins list page:

> A plugin that enables the use of vector tiles and mixed tiles with slippy maps and Flutter

... is that ok for you?

I'll add your plugin to the list when I receive a few more responses from other plugin authors!

**Comment by greensopinion** [comment]
> ... is that ok for you?

Sure, that would be great.

**Comment by JaffaKetchup** [comment]
Hi there,
I've just written the Vector Tiles page, and as you seem quite knowledgeable in the area, can you please check over [this page](https://flutter-map.vercel.app/miscellaneous/vector-tiles) to make sure it's correct?
Also, any other general about the new docs feedback would be appreciated.
Thanks!

**Comment by greensopinion** [comment]
JaffaKetchup,

Thanks for asking! It looks great and is accurate. Thinking that people reading this page will come with the goal of deciding whether to use vector or raster tiles, I recommend some changes. How about something like this:

## Vector Tiles

Maps are composed of a grid, where each square in the grid is a tile. `flutter_map` shows a map by selecting tiles for the desired viewport, and rendering them to the UI. Originally, all tiles were sourced from raster images, usually a png or jpeg. Raster tiles are excellent because they can represent any kind of data, render quickly, can be viewed without special software, and are readily available from most mapping services. Raster tiles have several limitations too. For example, they always have the same appearance so cannot be themed differently. Theming is used to accommodate light or dark mode, to fit in better with the look of an app, or to better suit the purpose of a specialized application. Raster tiles also have the disadvantage of becoming blurred (less sharp) when zoomed.

Vector tiles are a form of tile that represents data as a series of lines, polygons, points and text with metadata. Because they represent data and are not in a visual form, vector tiles can be rendered with any theme at any scale. This overcomes two major limitations of raster tiles. Vector tiles are also typically smaller and therefore make better use of internet bandwidth and storage. Vector tiles have the disadvantage of requiring specialized software to display, and are usually more computationally expensive to render. This can manifest itself as poor performance: slow to render maps, or skipped frames (jank) during animations such as pinching/zooming the map.

`flutter_map` does not support vector tiles directly, however a [community maintained plugin vector_map_tiles](https://github.com/greensopinion/flutter-vector-map-tiles) provides support for vector tiles. vector_map_tiles uses raster images during animations to improve performance, and vector rendering to provide sharp visuals and custom theming.

**Comment by JaffaKetchup** [comment]
I have taken your advice and modified the page: https://flutter-map.vercel.app/miscellaneous/raster-vs-vector-tiles.
As before, any other general about the new docs feedback would be greatly appreciated.
Thanks :)

**Comment by greensopinion** [comment]
Nice work! Looks fantastic.

You may want to change the following:

* I haven't seen vector tiles in SVG - commonly used are `*.mvt` or `*.pbf` file extensions, more detail at https://docs.mapbox.com/vector-tiles/specification/#format
* parsing vector tiles is not not a big contributor to the poor performance of vector tiles

Thanks again for your work on improving the docs!
