### ISSUE TITLE
Caching issue? Trying to display stacked overlays

### ISSUE THREAD

**Issue by chikamichi** [greensopinion/flutter-vector-map-tiles#152]
Hi,

Thank you for the library 👍 
I have an issue that I think is related to `VectorTileLayer` and the underlying caching mechanism.

### Context

I’m trying to display stacked, transparent vector "overlays" on top of a raster WMTS base layer:

```
 ^  GeoJSON polygons    ━━ polygons (PolygonLayer)
 │  roads               ━┓
 │  …                    ┃ overlays (VectorTileLayer)
 │  cadastre            ━┛
 │  base_layer          ━━ base layer (TileLayer)
```

where the base layer is always active, and each overlay may be toggled on/off.

My current implementation [is available here](https://github.com/kaibun/tmp-pub), it builds upon https://github.com/greensopinion/flutter-vector-map-tiles-examples.

### Issue

In principle it works fine, in practice it fails at properly toggling on/off the overlay layers. I feel like that might a caching issue.

- ✅ When starting with no overlays, then activating a first overlay, it loads and displays fine on top of the base layer.
- ❌ When enabling a second overlay, it loads fine but does not always displays fine (inconsistent behavior).
- ❌ When disabling the first overlay, the second (still enabled) overlay does not display fine.
- ❌ When moving around the map, the second (still enabled) overlay sometimes displays fine.
- ❌ When zooming in/out, the same inconsistent behavior.
- ❌ When enabling the first overlay again, it seems to load fine but displays the same data as the second overlay until moving to uncached tiles and/or zooming in/out to uncached tiles level.

All in all, it seems like the first enabled overlay loads and displays fine, but then that source/provider and the displayed tiles are cached and from there: 1/ the other overlays reuse that same data for any cached tile (location & zoom level wise) 2/ when moving around or in/out, it sometimes loads and displays the expected (refreshed, new source/provider) data, but not always.

_Note: The GeoJSON layer (a `PolygonLayer`) is "by design" a transparent overlay as well and works fine no matter what, that’s why I feel like the issue is rooted in flutter-vector-map-tiles (ie. the way I use it, arguably not the proper way ;))_

### Question

How could I properly implement toggable vector overlays?

The goal here is to load them (from network or cache store) on demand. I _could_ pre-load and display them all at once at widget’s startup, then use `Opacity` to mimic toggling on/off, but I’d rather not (bad UX due to loading and bandwidth footprint, not scalable, and also not really a working workaround from testing it).

Thank you!

### Dataset

- Vector tiles styles (overlays): 🇫🇷 https://geoservices.ign.fr/documentation/services/api-et-services-ogc/tuiles-vectorielles-tmswmts/styles ([source code](https://github.com/kaibun/tmp-pub/blob/main/lib/map_loader.dart#L99-L133))
- Raster tiles (base layer): 🇫🇷 https://igngp.geoapi.fr/ ([source code](https://github.com/kaibun/tmp-pub/blob/main/lib/map.dart#L60-L70))

**Comment by mvarendorff** [comment]
I am hitting something that feels similar in our project as well. Unfortunately your implementation link sends me to a 404 so I cannot verify if this is indeed the same issue.

In our app, we have two layers with different tileProviders and different themes but rendering for the lower layer only works if the upper layer is not included in the stack.

**Comment by greensopinion** [comment]
@mvarendorff you're right, the static theme variable is used to support isolates. The idea is that we want to offload tasks without having to transmit a copy of the theme every time we offload a task onto an isolate.

Dedicated isolates are created for each `VectorTileLayer` so if it's working correctly it shouldn't be a problem to have multiple flutter maps or a single map with multiple `VectorTileLayer`s each using a different theme. That is, unless you're running the app in debug mode. In debug mode, isolates aren't used since they perform horribly (some isolate optimizations aren't available in debug mode.) This is where the isolate decision is made: [executor.dart#L55](https://github.com/greensopinion/executor_lib/blob/74c0eab5519736d4b1a8094c072c7acad6ec62c0/lib/src/executor.dart#L55)

It's easy enough to test it out. You can either try running the app in release mode, or look for `newExecutor` in this library and replace it with `PoolExecutor(concurrency: concurrency)`

**Comment by mvarendorff** [comment]
I see! Is there any chance to bring development and production closer together perhaps? I haven't yet tried out the dev experience with the change you proposed (in the long term I'd rather not keep a fork around for this), so I am not sure *how* bad the performance is.

I also found a flaw with the suggestion I proposed in my previous comment about joining everything into a single theme; since everything is the same theme, it also generates the same key seemingly leading Flutter to sometimes re-use TileWidgets across multiple layers. Splitting the themes and running in production has everything work but is *really* confusing in development.

**Comment by greensopinion** [comment]
Things may have changed since we decided not to use isolates in debug mode. Feel free to try it out and issue a PR.

**Comment by greensopinion** [comment]
I've provided a multi-layer example: https://github.com/greensopinion/flutter-vector-map-tiles-examples
See https://github.com/greensopinion/flutter-vector-map-tiles-examples/blob/main/lib/examples/multi_layer.dart for details.

Feel free to reopen this issue or open a new one if needed.
