### ISSUE TITLE
Self host vector server

### ISSUE THREAD

**Issue by carlodenardin** [greensopinion/flutter-vector-map-tiles#34]
I have some trouble since I want to use my custom tile server. I created a custom server with OpenMapTiles. Now I want to use this server in my application.

I tried to use the example file to understand better how to use the `vector-map-tiles` package but I retrieved some problems.

```
@override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Column(
        children: [
          Flexible(
            child: FlutterMap(
              options: MapOptions(
                center: LatLng(41.301710, 19.795678),
                zoom: 10,
                maxZoom: 15,
                plugins: [VectorMapTilesPlugin()]
              ),
              layers: <LayerOptions>[
                VectorTileLayerOptions(
                  theme: ProvidedThemes.lightTheme(),
                  tileProviders: TileProviders(
                    {
                      'openmaptiles': MemoryCacheVectorTileProvider(
                        delegate: NetworkVectorTileProvider(
                          urlTemplate: 'http://<my_ip>:8080/styles/basic-preview/{z}/{x}/{y}.png',
                          maximumZoom: 14
                        ),
                        maxSizeBytes: 1024 * 1024 * 2
                      ),
                    }
                  )
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

```

Error:
```
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io[/path_provider]())
#0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:165
<asynchronous suspension>
#1      getTemporaryDirectory (package:path_provider[/path_provider.dart:55:24]())
<asynchronous suspension>
#2      ByteStorage._storagePath (package:vector_map_tiles[/src/cache/byte_storage.dart:20:25]())
<asynchronous suspension>
#3      ByteStorage.fileOf (package:vector_map_tiles[/src/cache/byte_storage.dart:32:18]())
<asynchronous suspension>
#4      ByteStorage.write (package:vector_map_tiles[/src/cache/byte_storage.dart:42:18]())
<asynchronous suspension>
#5      StorageCache.put (package:vector_map_tiles[/src/cache/storage_cache.dart:39:5]())
<asynchronous suspension>
#6      VectorTileLoadingCache._loadBytes (package:vector_map_tiles[/src/cache/vector_tile_loading_cache.dart:87:7]())
<asynchronous suspension>
```

I'm posting also the Tileserver-gl since is just a debug server to understand how to work with maps: http://46.101.253.155:8080

**Comment by ibrierley** [comment]
Is this on flutter web, or a mobile device ? Just wondering from the error if its because there's an io feature that can't be available in the browser ?

**Comment by greensopinion** [comment]
@carlodenardin thanks for the issue. Can you confirm that you can run the [example app](https://github.com/greensopinion/flutter-vector-map-tiles/tree/main/example)?

Perhaps you could include the output from `flutter doctor -v` and the contents of your `pubspec.yaml`

**Comment by greensopinion** [comment]
`HTTP 403` is the server rejecting the HTTP request. I'm not sure why you'd get that from Stadia maps, but perhaps it's something related to using an appropriate API key.

> InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).

I'm not sure why this is coming up from you, perhaps there's something wrong in one of the protobuf tiles. I've had cases where tile data wouldn't load due to a half-written file in the file cache. From what I could guess, it was due to terminating an app while the file was being written to disk. You may want to clear out the file cache and try again.

As for the original issue, it should be straight forward to troubleshoot by putting a breakpoint where the plugin is loaded. You'll be able to see which platform is being used, and from there figure out why the plugin isn't available. I'm glad that you can run the example, please post what you learn back here so that others can benefit if they run in to the same problem.

From the output of `flutter doctor` it looks like you're running an unreleased version of Flutter. If all else fails, you may want to try running with a released version since that is what we test with.

Closing since this does not appear to be a defect with this plugin.
