### ISSUE TITLE
Performance improvement for tablet

### ISSUE THREAD

**Issue by jean-gblr** [greensopinion/flutter-vector-map-tiles#48]
Hello,

We are currently using flutter_map with raster maps from mapbox. But in order to reduce our mapProvider cost we are planning to deploy our own server. Which led us to explore the idea of only serving vectors and let the client app do the rendering.

To that objective I knew about your plugin, problem is our users are using tablets. I saw you wrote in the readme about the performance issues on tablet (that I tested too).

We really need a vector map that works well for our project. So I am down to try and help finding ways to improve performance, either on your repo or on a fork.

Do you have any ressources, blogs, lines of code pointing to where you think there is improvement possible ?

Thanks in advance

**Comment by greensopinion** [comment]
Hi thanks for asking. Have you tried the latest version which has improved performance over prior versions? If so, what do you think - is it good enough for the tablets you're targeting?

You may be interested to hear that this plugin uses isolates, but not if the app is running in debug mode - so you'll want to test it using release mode on a real device to understand what it will be like for users. Also the theme can make a difference,  so consider experimenting with different themes.

> I am down to try and help finding ways to improve performance, either on your repo or on a fork.

Any contributions are most welcome!

> Do you have any ressources, blogs, lines of code pointing to where you think there is improvement possible ?

The best place to start is running the example application with the profiler. I use the command:

`flutter run --profile --no-dds` 

You'll need to run the example app on an actual device (not in a simulator)
There are some great tips on performance profiling here: https://docs.flutter.dev/perf

The biggest bottleneck at the moment is text layout. I have some ideas that I'm working on to reduce jank due to text layout.

There are likely other opportunities to improve performance which you'll be able to identify with the profiler. Ideas and PRs are welcome.

**Comment by jean-gblr** [comment]
Alright thanks for all the informations, some folks and I are gonna look into it and come back here to report any news :D

**Comment by FaFre** [comment]
Maybe it would make sense to introduce some additional render options to control performance hungry features. 
For example render street names of small and medium roads only when zoom > config.

I think the layout of text elements will always be a big performance problem, until there are some decent improvements inside the flutter framework. It's just extremely slow and old devices will suffer a lot, even with optimized caching and all.

Are poly-lines already getting simplified using e.g. https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm?

**Comment by greensopinion** [comment]
@FaFre you're right, text rendering is quite expensive. The latest release of this library (1.5.0) improves how text layout is computed by spreading the work over multiple frames. In my testing this has reduced jank significantly.

The map theme has a big effect on performance. There are a few tips in [this comment](https://github.com/greensopinion/flutter-vector-map-tiles/issues/10#issuecomment-955761176) on designing a map style to improve rendering fame rate.
The profiler can shed insight into which map features are creating the most overhead.

**Comment by FaFre** [comment]
That's really cool, also the `TextApproximation` is very nifty. I really enjoyed reading some of the code. I think I will replace the raster layer with your plugin now and see if I'm able to contribute some ideas or code.

I could not resist seeing what happens, when I take my simplification algo from my other project (where I use it for polygon before polygon painting), and see what happens if I put the optimization to very aggressive.

This is is the optimized version that simplifies with a tolerance of 50 in the tile coord system right after decoding:
https://user-images.githubusercontent.com/59543085/166553033-742a0730-902b-4738-b3a3-eea6f7623ba7.mp4

This is the same example code, but without the optimization:
https://user-images.githubusercontent.com/59543085/166553300-b8e9ce38-f2eb-4897-8b7e-7f6ea9723e44.mp4

**Comment by greensopinion** [comment]
Glad you're enjoying it :D There's a lot of room for improvement in the code quality in that area, but I'm not sure if I'll get to it anytime soon since it's working well enough at the moment.

The optimized version seems to have a slower frame rate than the non-optimized version. Not sure if that's because of screen capture.

Here's an example that I recorded recently https://twitter.com/dgreen/status/1518814744341213185
That one doesn't include the latest improvements but it still looks smoother to me. It's probably because the theme is more efficient but I haven't checked. 
In case you want to try it I used the "Mapbox Streets" theme for that recording, you can see it here in the [gallery](https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/gallery/gallery.md)

**Comment by FaFre** [comment]
I tried mapbox streets and it's running much smoother compared to the shipped light theme :) However, I experience very high memory peaks when using this theme:

![image](https://user-images.githubusercontent.com/59543085/167046335-5ab4b693-bb59-44a4-9450-d53b23ba8cba.png)

That's 2.6GB in memory for raster pictures. Often the app crashes right after startup, and scrolling a few pixels:
```
E/Adreno-GSL(13911): <gsl_memory_alloc_pure:2604>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
W/Adreno-GSL(13911): <gsl_ldd_control:553>: ioctl fd 72 code 0xc0300945 (IOCTL_KGSL_GPUOBJ_ALLOC) failed: errno 12 Out of memory
```
My device has 8GB of memory, which should be more than enough.

It's kinda random and doesn't appear every time, with higher zoom levels it is more likely to happen, like:
```dart
MapOptions(
                center: LatLng(48.9480, 9.4474),
                zoom: 18.0,
                plugins: [VectorMapTilesPlugin()])
```
I tried to find out more, but google doesn't know much about this error, and what it causes.

**Comment by greensopinion** [comment]
What you're seeing looks a lot like issue #24 

I recommend checking:
1. you're using `VectorTileLayerOptions(tileOffset: TileOffset.mapbox)`
2. the maxZoom of `MapOptions(maxZoom: 22)` matches maximumZoom of `NetworkVectorTileProvider(maximumZoom: 22)`

I suspect that you have a mismatch between `maxZoom` and `maximumZoom` of your tile provider, per recommendation 2 above.

Give it a try and let me know how it works out.

**Comment by greensopinion** [comment]
Closing until we get some actionable feedback. Feel free to comment/reopen if you're still experiencing the issue.

**Comment by FaFre** [comment]
> What you're seeing looks a lot like issue #24 
> 
> I recommend checking:
> 1. you're using `VectorTileLayerOptions(tileOffset: TileOffset.mapbox)`
> 2. the maxZoom of `MapOptions(maxZoom: 22)` matches maximumZoom of `NetworkVectorTileProvider(maximumZoom: 22)`
> 
> I suspect that you have a mismatch between `maxZoom` and `maximumZoom` of your tile provider, per recommendation 2 above.
> 
> Give it a try and let me know how it works out.

The adjustment of the zoom solved the problem. Thanks!

Would it make sense to print a warning in this case, indicating that the parameters are different? Both access to maxZoom from the TileProvider and the MapOptions is give at some point.
