### ISSUE TITLE
Does not render symbol

### ISSUE THREAD

**Issue by jean-gblr** [greensopinion/flutter-vector-map-tiles#55]
Hello again, btw I wanna say huge thanks to you for the performance improvements you made. We're back on flutter map since we need labels on polyline, which Gmaps can't do.

We have a problem now with rendering POI and other symbols. For example it does not render house number
`{
      "id": "housenumber",
      "type": "symbol",
      "source": "openmaptiles",
      "source-layer": "housenumber",
      "minzoom": 17,
      "layout": {"text-field": "{housenumber}", "text-size": 6}
    },`

It does work on maputnik, but not on your code. Do you know if it's a bug or just not implemented ?

**Comment by greensopinion** [comment]
Hey @jean-gblr you're welcome!

Have you checked to ensure that your map is zooming to level 17 (`minzoom` above)
Other things to look at: is the source layer available in the tileset? Is the text field `housenumber`?

Consider adding a `paint` property, since this library won't draw text without it:

```json
          "paint": {
            "text-halo-color": "#fff",
            "text-color": "#212121",
            "text-halo-width": 4
          }
```

Last resort, you can put a breakpoint at [symbol_point_renderer.dart#L39](https://github.com/greensopinion/dart-vector-tile-renderer/blob/main/lib/src/features/symbol_point_renderer.dart#L39) and see if that helps.

Let me know if you figure it out.

**Comment by greensopinion** [comment]
closing, but feel free to reopen or comment if this continues to be an issue
