### ISSUE TITLE
Custom Mapbox styles don't apply

### ISSUE THREAD

**Issue by alkaitagi** [greensopinion/flutter-vector-map-tiles#65]
I've tried to use the plugin with custom styles which I've created in Mapbox Studio and then downloaded as `.json`s. Unfortunately, this plugin doesn't seem to apply the styles as the map displays with the default Mapbox Light and Dark (i.e. not dimming texts and borders like I've specified in my styles).

For references, this is how my custom light map should look:
<img width="282" alt="image" src="https://user-images.githubusercontent.com/32439229/176758447-96bcfd23-ca19-4017-9589-49492bb4b656.png">
 
I've made a minimal repo to demo the issue: https://github.com/alkaitagi/vector_map_test/tree/master/lib. I'll appreciate any help.

**Comment by greensopinion** [comment]
There was a bug introduced a few days ago, since fixed, that prevented some themes from working. You may want to try the latest version `2.1.2` to see if that resolves the issue for you.

**Comment by alkaitagi** [comment]
I have updated the package and once again checked the URL. I see only see default style without my customization. No errors shows up on the console. I think you were too early to close this issue since the problem is not resolved.

**Comment by greensopinion** [comment]
@alkaitagi I've created an example that uses mapbox. Let me know if that makes a difference for you.

https://github.com/greensopinion/flutter-vector-map-tiles/tree/mapbox-example

This is the commit with the relevant changes: 00cdb615e545c43a

This is what it looks like:

<img width="912" alt="Screen Shot 2022-07-08 at 7 39 34 AM" src="https://user-images.githubusercontent.com/18102398/178014391-1e2426e3-b049-4c96-b2da-b442dcc7162c.png">

**Comment by alkaitagi** [comment]
No, this still doesn't work for custom styles created with Mapbox Studio. It only applies the default theme (dark) instead of my own theme is based off it, like it is described in the original post on this issue. No errors are present in the console. I suggest you create your own theme _(e.g. change country borders from solid to dashed)_ and try making that work.

Also, believe me I appreciate your communication and intention to help, but why is this issue still being held as closed while clearly the problem is not resolved.

**Comment by greensopinion** [comment]
@alkaitagi I've had a go with a custom theme, I made the streets red. Here's the result:

<img width="1266" alt="Screen Shot 2022-07-16 at 3 51 07 PM" src="https://user-images.githubusercontent.com/18102398/179374266-fb5fe764-c198-46cb-b114-675efc7592b6.png">

To get that to work you will need to get the style using an URL that looks something like this: `https://api.mapbox.com/styles/v1/greensopinion/cl5oh4q3t000216o0tc9cngxh?access_token=$mapboxApiKey`
You'll also need to publish your custom theme (so that it's available in production on mapbox)

See 51614575534a74c8c17f21ed97be499c70c34b91 which demonstrates how to use a custom theme.

> why is this issue still being held as closed while clearly the problem is not resolved

The issue is still closed because it looks like there isn't a problem with this library. I'm happy to reopen it if there's clearly a problem, but in this case there has been a lack of data pointing to a problem.
