### ISSUE TITLE
Street names not correctly displayed at certain zoom-levels

### ISSUE THREAD

**Issue by FaFre** [greensopinion/flutter-vector-map-tiles#7]
I was exploring around on the map with the example application (native Linux). 
Some street names are displayed incorrectly at certain zoom levels:

![image](https://user-images.githubusercontent.com/59543085/124102825-e3f8af80-da8a-11eb-89f6-03ddfbc220c6.png)

Is this a hard to tackle problem (I haven't had the time to look at the code or the rendering of the tiles s far...)?
Are there other known issues at the moment (I understand the package is in early stage)?

**Comment by greensopinion** [comment]
Thanks for the issue. What you're seeing is labels that are rendered at the edge of a tile, with some part of the label being rendered off-tile.

The easiest way to address this issue would be to change tile rendering so that labels are not rendered at the edge of a tile, either by skipping the label completely, by moving the label, or a combination. 

Alternatively, we could look at eliminating clip around tiles so that labels can render over the edge of a tile. That would be a bigger change, and I'm not sure how it would work with transparency in the map theme.

A good place to get started is the [dart-vector-tile-renderer](https://github.com/greensopinion/dart-vector-tile-renderer) project, which this project uses to render tiles.

As for known issues, this is one. Feel free to create more issues as you discover them.

**Comment by greensopinion** [comment]
If you're interested in contributing, this code is used to avoid rendering labels over top of each other: [label_space.dart](https://github.com/greensopinion/dart-vector-tile-renderer/blob/main/lib/src/features/label_space.dart#L6)

**Comment by greensopinion** [comment]
I've made some improvements for horizontal labels but it's not corrected for all situations.

**Comment by greensopinion** [comment]
This issue should now be fully addressed with https://github.com/greensopinion/dart-vector-tile-renderer/commit/e9ae79d8f12f3200fd30a91bfdfbfbc54a3ec2f3
