### ISSUE TITLE
Improvement of tile caching

### ISSUE THREAD

**Issue by FaFre** [greensopinion/flutter-vector-map-tiles#80]
This is just a rough idea I had today while working with some sqlite data. I felt like sharing this here, although the impact might be insignificant and as well has a low priority for the project.

At the moment the project uses the standard filesystem for caching tiles. As performance is always an topic here, we might can squeeze out some time for read/write operations, and have the option to add some more metadata to cached tiles, for example ttl, or preprocessed render data.

There is a great package that thinly wraps around sqlite using ffi (https://pub.dev/packages/sqlite3) which supports all platforms, including web (experimental).

There are some benchmarks comparing sqlite to fs performance like https://www.sqlite.org/intern-v-extern-blob.html and https://www.sqlite.org/fasterthanfs.html

Mapbox has a specification for storing tilesets inside an sqlite database https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md which might could get applied.

Benefits of sqlite:
1. Very portable, tiles could be bundled server-side and delivered as a single database for e.g. offline-use
2. Storing additional metadata like cache ttl, or preprocessed render data
3. Possible improvement of reading or writing tiles
4. Could bring some additional features/securities with locks, when working with isolates and having parallel operations

**Comment by greensopinion** [comment]
Hey @FaFre thanks for the idea. So far I haven't found the filesystem to be a bottleneck, but maybe that's not the case for everyone.

At the moment there is no way to remove the filesystem-based cache, however there is an experiment showing how it can be done on #77. In #77 the filesystem cache is not used on the web platform. It should be relatively easy to disable it on all platforms so that you can try out something different.

`VectorTileProvider` is one place that you can plug in your own code without having to modify the library. For example, you're free to provide your own `VectorTileProvider` that provides caching. `MemoryCacheVectorTileProvider` provides a good example that separates tile retrieval from caching: https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/lib/src/vector_tile_provider.dart#L79

**Comment by FaFre** [comment]
Thanks for your feedback! Alright, I haven't looked into the source too much yet, but it seems to be possible then, to outsource the caching into another plugin. I will try some things when the time has come and return with news. Closing this for now.
