### ISSUE TITLE
Ui freeze when panning and zooming

### ISSUE THREAD

**Issue by Pepslee** [greensopinion/flutter-vector-map-tiles#93]
I use maptiler server to get `'https://api.maptiler.com/tiles/v3/{z}/{x}/{y}.pbf?key=$apiKey'` tiles and also style 
`ThemeReader(logger: const Logger.console()).read(json_style!)`.
But there a lot of freezes when I`m trying to pan or zoom map.
I have built release apk and set `concurrency: 4`  but it doesn't help.

**Comment by Pepslee** [comment]
![image](https://user-images.githubusercontent.com/13853798/193452478-cd6f905a-bc1e-4d6f-ba74-994bc8aa4928.png)
and I have some error when zooming

**Comment by greensopinion** [comment]
Could you attach your JSON style?

It would also be helpful if you could run the application in the profiler and provide screenshots of the profiling results from the performance page (e.g. stack frames for sample slow frames)

Were you running the application in debug mode or release mode? It makes a difference with maps, since debug mode does not use isolates. You may want to try with release mode to see if that makes a difference.

**Comment by Robbendebiene** [comment]
I'm running the example app in release mode on a Pixel 6 and also get a lot of stuttering/jank when new tiles are rendered.

Here is a screenshot from the performance page while running in profile mode:

![grafik](https://user-images.githubusercontent.com/13716661/193802685-1f27838b-e8f1-483a-8c9e-c2ea59b94d38.png)

Full performance trace: [dart_devtools.zip](https://github.com/greensopinion/flutter-vector-map-tiles/files/9705270/dart_devtools.zip)

**Comment by greensopinion** [comment]
Thanks for providing the profiling results, that's really helpful

> I'm running the example app in release mode

The example app uses a theme that has a lot of overhead. In your profiling results, you can see that a lot of slow frames are caused by the raster thread, which is an indication that there is a lot of work to do because of the level of detail in each tile.
I recommend trying it with a different theme. 

Some tips for optimizing themes are listed here: https://github.com/greensopinion/flutter-vector-map-tiles/issues/10#issuecomment-955761176

other things to keep in mind:
* dashed paths are expensive
* constants in theme expressions are cached
* the profiler will help to identify problem areas

If a different theme doesn't produce the results that you're looking for, feel free to dig into the code to see if you can improve it.

**Comment by Robbendebiene** [comment]
Thanks for your answer.

So this package still suffers from the problem, that rendering cannot be done in a different thread I guess? (https://github.com/flutter/flutter/issues/10647) What exactly is currently done in separated threads?

There are some [workarounds](https://github.com/flutter/flutter/issues/13937#issuecomment-1155630152) mentioned here, but they are limited to Android and iOS only.

**Comment by greensopinion** [comment]
> So this package still suffers from the problem, that rendering cannot be done in a different thread I guess? ([flutter/flutter#10647](https://github.com/flutter/flutter/issues/10647)) 

That's part of it. In your profiling results you can see that even if we were able to do everything on another thread, the raster thread would still be a bottleneck. One way to solve that issue is for each frame to do less work, which can be accomplished by tuning the theme as mentioned above. 

There is an experimental feature that you could look at, delaying rendering specific layers in the theme. This is already done for text, but could be used for other layers too. For example, you could have buildings rendered after a small delay. It's not fully baked but is an idea that might be helpful.
You can find out more about this feature here: https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/lib/src/grid/tile_layer_composer.dart#L56

> What exactly is currently done in separated threads?

This is a good place to start looking: https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/lib/src/executor/executor.dart#L24

> There are some [workarounds](https://github.com/flutter/flutter/issues/13937#issuecomment-1155630152) mentioned here, but they are limited to Android and iOS only.

Thanks!
